#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

env \
  DEADLINE_LOCAL="${DEADLINE_LOCAL:-2026-02-28 17:00:00}" \
  MAX_CYCLES="${MAX_CYCLES:-1}" \
  RUN_REVIEW_GATE="${RUN_REVIEW_GATE:-0}" \
  RUN_DATA_PULL="${RUN_DATA_PULL:-0}" \
  RUN_EXTERNAL_BENCHMARK="${RUN_EXTERNAL_BENCHMARK:-1}" \
  RUN_ADMISSION="${RUN_ADMISSION:-1}" \
  RUN_FAILURE_BREAKDOWN="${RUN_FAILURE_BREAKDOWN:-1}" \
  RUN_OPTIMIZE_LOOP="${RUN_OPTIMIZE_LOOP:-1}" \
  RUN_HEALTH_CHECK="${RUN_HEALTH_CHECK:-1}" \
  CONTINUE_ON_ERROR="${CONTINUE_ON_ERROR:-1}" \
  OPTIMIZE_DIRECTION_MODE="${OPTIMIZE_DIRECTION_MODE:-adaptive}" \
  OPTIMIZE_TOP_K="${OPTIMIZE_TOP_K:-2}" \
  OPTIMIZE_MAX_RUNS_PER_CARD="${OPTIMIZE_MAX_RUNS_PER_CARD:-4}" \
  OPTIMIZE_SKIP_WATCH="${OPTIMIZE_SKIP_WATCH:-1}" \
  OPTIMIZE_DRAIN_QUEUE_FIRST="${OPTIMIZE_DRAIN_QUEUE_FIRST:-1}" \
  OPTIMIZE_EXECUTE="${OPTIMIZE_EXECUTE:-1}" \
  OPTIMIZE_CONTINUE_ON_ERROR="${OPTIMIZE_CONTINUE_ON_ERROR:-1}" \
  OPTIMIZE_ALLOW_REPEAT_CARDS="${OPTIMIZE_ALLOW_REPEAT_CARDS:-1}" \
  QUEUE_DRAIN_MAX_ITEMS="${QUEUE_DRAIN_MAX_ITEMS:-2}" \
  QUEUE_DRAIN_CONTINUE_ON_ERROR="${QUEUE_DRAIN_CONTINUE_ON_ERROR:-1}" \
  bash scripts/sprint_push_until_deadline.sh >> logs/sprint_cron.log 2>&1
